---
kubeProxyReplacement: "strict"

k8sServiceHost: cluster01.dfw.56k.sh
k8sServicePort: 6443

ipam:
  mode: "kubernetes"

bgp:
  enabled: false
  announce:
    loadbalancerIP: true

hubble:
  enabled: false

ipv6:
  enabled: false
